@ECHO OFF

:INPUT_START
ECHO SET ABC???
SET ABC_STR=
SET /P ABC_STR=
IF "%ABC_STR%"=="" GOTO :INPUT_START

xcopy /e /y default ABC%ABC_STR%\

:NEXT_INPUT_START
ECHO SET PROBLEM
SET PROB_STR=
SET /P PROB_STR=
IF "%PROB_STR%"=="" GOTO :NEXT_INPUT_START

RENAME ABC%ABC_STR%\A %PROB_STR%